// <auto-generated />
namespace EFAcademy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class manymany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manymany));
        
        string IMigrationMetadata.Id
        {
            get { return "201708021731070_many many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
