//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Required]
        public int ID { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string name { get; set; }
        public System.DateTime JoiningDate { get; set; }
        [DisplayFormat(DataFormatString = "{0::MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Range(18, 60)]
        public int Age { get; set; }
        public string Country { get; set; }
    }
}
